title: zsdnishishui的博客
description: "个人博客"
author:
  name: "zsdnishishui"
  email: "someone@somewebsite.somedomain"
  url: "https://zsdnishishui.github.io"

baseurl: /

source: .
destination: ./_site
permalink: /:title
paginate: 10
paginate_path: /page/:num/
google_analytics: false
baidu_analytics: true
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

future: true
plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap

# Custom variables
owner : "zsdnishishui"
year : "2023"
